GET https://registromicroservicio-production.up.railway.app/api/materias/listar HTTP/1.1

###
POST https://registromicroservicio-production.up.railway.app/api/materias/buscar
Content-Type: application/json

{
    "asignatura_id": 1
}

###
POST https://registromicroservicio-production.up.railway.app/alumnos/login
Content-Type: application/json

{
    "email": "alumno@example.com",
    "password": "TuPasswordAqui"
}

###
POST https://registromicroservicio-production.up.railway.app/alumnos/password
Content-Type: application/json

{
    "email": "223074@ids.upchiapas.edu.mx",
    "password": "Alumno"
}